### PR TITLE
React 0.14 support

### PR DESCRIPTION
**Pull request by miraks**
There are warnings because this component use React instead of ReactDOM, but I think we should wait until React 0.14 release and then switch to ReactDOM.

### CODE REVIEW

**Comment by wangzuo** [comment]
Yes, lets wait and leave this open for now.

**Comment by williamcotton** [comment]
:+1:

**Comment by miraks** [comment]
React 0.14 has been released, so I updated this PR with removed React 0.13 support and fixes for deprecation warnings.

**Comment by wangzuo** [comment]
Thank you so much.

**Pull request merged**
