### PR TITLE
Fix restoring cursor when props.text

### PR DESCRIPTION
**Pull request by bitspook**
@wangzuo Please check the app before merging this commit. I am pretty sure it will work, but I haven't checked it. I have created an ES6 fork of this project (https://github.com/channikhabra/react-medium-editor-es6/) and am using that. Creating this PR to save you some time with #18

### CODE REVIEW

**Comment by ilyadoroshin** [comment]
@channikhabra thanks man! worked great for me :+1:

**Comment by bassettsj** [comment]
:+1:

**Comment by gregegan** [comment]
:+1:

**Comment by fmvilas** [comment]
Any plan to merge it @channikhabra @wangzuo?

**Comment by fmvilas** [comment]
Thanks! I will be heavily using this component in the next months, let me know if you need help to maintain it.

**Comment by MartijnHols** [comment]
Is this still needed? What does it do anyway? I had to revert the changes made by this PR because it broke adding text to new `li`s (the text after the first character was being added to the front of the next element).

**Edit:** Seems I'm not the only one experiencing issues with this change: https://github.com/yabwe/medium-editor/issues/1129#issuecomment-231423102

**Pull request merged**
